config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :products do
    resources :comments
  end

  resources :users
  resources :payments
  #resources :payments, only:[:create]

  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'
  get 'static_pages/landing_page'

  post '/payments/create'

  root 'static_pages#landing_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mynewapp</title>

    <script src="https://use.typekit.net/kgz1wnu.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-fixed-top" role="navigation"> 
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>    
          </button>
        </div>

        <!--<%= link_to "Bike Berlin", static_pages_landing_page_path, :class => "navbar-brand" %>-->
        <div class="navbar-brand">
          <a href= "<%= static_pages_landing_page_path %>">Bike Berlin</a>
        </div>

        <div class="navbar-collapse collapse in " id="navbar-collapse-1">
          <ul class=" nav navbar-nav navbar-left">
            <li class="one"><%= link_to "Products", products_path %></li>
            <li class="two"><%= link_to "About", static_pages_about_path %></li>
            <li class="three"><%= link_to "Contact",static_pages_contact_path %></li>
          </ul>

          <ul class="nav navbar-nav pull-right">
            <li>
            <%= form_tag("/products", method: "get", :class => "search-form") do %>
              <%= text_field_tag(:q) %>
              <%= submit_tag("Search", :id => "search-btn") %>
            <% end %>
            </li>
            <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>

          </ul>
        
        </div><!--end navbar-collapse-->
      </div>
    </nav>


    <% if notice %>
      <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

  	<footer class="lightgrey-bg footer navbar-fixed-bottom">
      <div class="container pad-top-quarter pad-bottom-quarter">
  		  <div class="row">
          <div class="col-lg-5 col-md-12"> 
            <h4>Bike Berlin</h4>
            <p class="small-font">Your source for used bikes in Berlin.</p>
          </div>
          <div class="col-md-5 col-lg-offset-2 col-md-12">
            <h4 class="copywright">&copy;<span class="small-font"> 2016 Bike Berlin</span></h4>
          </div>
        </div>
      </div>
  	</footer>
  </body>
</html>